version: '3.9'

services:

  app:
    build:
      context: ./app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - REACT_APP_ENVIRONMENT=prod


  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    

